name: Python Test

on:
  push:
    branches: [ saroosh ]
  pull_request:
    branches: [ saroosh ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install pylint
        pip install black

    - name: Run tests with pytest
      run: pytest unittesting/test_cases.py

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: pytest.xml

    - name: Run pylint
      run: pylint setup.py
    - name: run Black
      run: black unittesting/test_cases.py

    # - name: Merge to master branch
    #   if: ${{ success() }}
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     token: ${{ secrets.ACCESS_TOKEN }}
    #     branch: master
    #     commit-message: "Merge saroosh branch"
    #     title: "Merge saroosh branch"
    #     body: "This is an automated pull request created by GitHub Actions."


